### ISSUE TITLE
View campaign page

### ISSUE THREAD

**Issue by wilinetan** [dsc-project-mr/mr-fe-internal#19]
**Description of feature/enhancement**
The upper half is the same as the campaign item component but expanded to show more description. the graph part is still tbc but u can just create the layout for it first for now
<img width="748" alt="Screen Shot 2022-12-08 at 12 05 04 AM" src="https://user-images.githubusercontent.com/51109678/206229749-9355f484-4486-4f04-9095-a8935fa16ea6.png">

_insert link to figma etc_
https://www.figma.com/file/9bUuKvk2xG359ru4sPY5US/Workspace?node-id=5830%3A51259&t=6Zw56wWVq5ij8PvW-0

**Comment by firwer** [comment]
Currently blocked, waiting for #22 merge to fully integrate dynamic routing
